# Numpy入门

## NumPy库的简介

In [7]:
import numpy as np
print(np.__version__)
np.show_config()
arr1 = np.array([1,2,3])
print(arr1.itemsize)
np.info(np.add)

1.18.1
4
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``ou

## NumPy简单入门 - 1 (ndarray / dtype)

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
arr1.shape

(5,)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.arange(2,5)

array([2, 3, 4])

In [22]:
np.arange(15)
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [28]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [29]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [31]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [32]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### exercise

In [61]:
import numpy as np
np.zeros(10)
np.arange(10, 50)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## NumPy简单入门-2 shape / reshape / 通用函数

In [36]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [37]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
arr.reshape(2,3).shape

(2, 3)

In [39]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [40]:
arr.reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
arr.reshape(6)

array([0, 1, 2, 3, 4, 5])

In [42]:
arr.reshape(-2)

array([0, 1, 2, 3, 4, 5])

In [43]:
arr.reshape(6,)

array([0, 1, 2, 3, 4, 5])

In [44]:
arr.reshape(-2,)

array([0, 1, 2, 3, 4, 5])

### ndarray与标量之间的运算

In [46]:
arr = np.array(([1, 2, 3], [4, 5, 6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [49]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [50]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 通用函数

In [51]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x = np.random.randn(8)
y = np.random.randn(8)

In [58]:
x

array([-1.6036397 , -0.62346979, -0.6039266 , -0.31065648,  0.18288534,
        0.59671585, -0.4032052 ,  0.48642252])

In [59]:
y

array([-1.9649951 , -0.26263833,  0.95238987, -0.68749167, -0.51668492,
       -0.02056019,  0.41318304, -0.03430577])

In [60]:
np.maximum(x, y)

array([-1.6036397 , -0.26263833,  0.95238987, -0.31065648,  0.18288534,
        0.59671585,  0.41318304,  0.48642252])

### exercise

In [63]:
import numpy as np
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## NumPy简单入门-3 切片 / 索引

### 切片

In [68]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[5]

5

In [70]:
arr[5:8]

array([5, 6, 7])

In [73]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [75]:
arr_slice_copy = arr[5:8].copy()
arr_slice_copy

array([12, 12, 12])

In [76]:
arr_slice_copy = 20
arr_slice_copy

20

In [77]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### 索引

In [79]:
# 多维数组
arr2d = np.arange(1, 10).reshape(3,3)
arr2d[2]

array([7, 8, 9])

In [80]:
arr2d[0][2]

3

In [81]:
arr2d[0,2]

3

In [82]:
arr3d = np.arange(1, 13).reshape(2,2,3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr3d[1, 0]

array([7, 8, 9])

In [85]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [88]:
arr2d[1,:2]

array([4, 5])

In [90]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [92]:
arr2d[:2,:1] = 0
arr2d

array([[0, 2, 3],
       [0, 5, 6],
       [7, 8, 9]])

### exercise

In [127]:
import numpy as np
# 8
arr1 = np.arange(4)
print(arr1[::-1])
# 15
arr2 = np.ones((4,4))
arr2[1:-1,1:-1] = 0
print(arr2)
# 19
arr3 = np.zeros((8,8), dtype='int32')
arr3[::2, ::2] = 1
arr3[1::2, 1::2] = 1
print(arr3)
# 70
arr4 = np.arange(1,6, dtype='int32')
arr5 = np.zeros(17, dtype='int32')
arr5[0::4] = arr4
print(arr5)

[3 2 1 0]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

## NumPy简单入门-4 布尔索引 / 花式索引

### 布尔型索引

In [128]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [129]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [130]:
data = np.random.randn(7, 4)
data

array([[-1.9322409 , -0.59993224,  2.56936355,  0.58939604],
       [-1.41523431,  0.37484267,  1.61613004, -0.09063043],
       [-0.17469543, -0.12849485, -0.07119596,  1.84385796],
       [ 0.14583875,  0.60027957,  0.7329657 ,  0.39006637],
       [ 0.24419693,  0.03894956,  0.16633206,  0.4115406 ],
       [ 0.11646356,  0.31566453,  0.26667484,  1.29092822],
       [-1.78495814,  0.63941875, -0.26545728,  1.80481455]])

In [131]:
data[names=='Bob', 2:]

array([[2.56936355, 0.58939604],
       [0.7329657 , 0.39006637]])

In [133]:
data[names=='Bob', 3]

array([0.58939604, 0.39006637])

In [134]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [137]:
data[~(names == 'Bob')]

array([[-1.41523431,  0.37484267,  1.61613004, -0.09063043],
       [-0.17469543, -0.12849485, -0.07119596,  1.84385796],
       [ 0.24419693,  0.03894956,  0.16633206,  0.4115406 ],
       [ 0.11646356,  0.31566453,  0.26667484,  1.29092822],
       [-1.78495814,  0.63941875, -0.26545728,  1.80481455]])

In [139]:
data[(names=='Bob') | (names == 'Will')]

array([[-1.9322409 , -0.59993224,  2.56936355,  0.58939604],
       [-0.17469543, -0.12849485, -0.07119596,  1.84385796],
       [ 0.14583875,  0.60027957,  0.7329657 ,  0.39006637],
       [ 0.24419693,  0.03894956,  0.16633206,  0.4115406 ]])

In [141]:
new_data = np.random.randn(5,5)
new_data

array([[ 0.19828954, -1.69213471, -0.18642281, -0.95068312, -0.71120864],
       [-0.46438813, -0.76125264,  0.9335613 ,  0.5050638 ,  0.24439021],
       [ 1.57142933, -0.29800136,  0.79758724,  0.35503096, -0.73345416],
       [ 0.32496342,  0.4559009 ,  0.51575217, -0.35197126, -2.07973357],
       [ 0.83532294, -0.56358766,  1.53578725, -0.35350434,  1.33425868]])

In [143]:
new_data[new_data < 0 ] = 0
new_data

array([[0.19828954, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.9335613 , 0.5050638 , 0.24439021],
       [1.57142933, 0.        , 0.79758724, 0.35503096, 0.        ],
       [0.32496342, 0.4559009 , 0.51575217, 0.        , 0.        ],
       [0.83532294, 0.        , 1.53578725, 0.        , 1.33425868]])

### 花式索引

In [147]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] =i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [148]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [150]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [154]:
a = arr[[1,5,7,2], [0,3,1,2]]
a

array([ 4, 23, 29, 10])

In [156]:
a[0] = 5
a

array([ 5, 23, 29, 10])

In [157]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

### exercise

In [186]:
# 25
arr = np.arange(1, 10)
arr[(arr >= 3) & (arr <= 8)] *= -1
print(arr)

# 75
arr2 = np.arange(12).reshape(4,-1)
for i in range(4):
    arr2[i] = i
arr2[[1,3]] = arr2[[3,1]]
print(arr2)

[ 1  2 -3 -4 -5 -6 -7 -8  9]
[[0 0 0]
 [3 3 3]
 [2 2 2]
 [1 1 1]]


## NumPy简单入门 - 5 (数学统计学函数 / sort)

### code

In [1]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
arr.mean()

4.0

In [3]:
np.mean(arr)

4.0

In [4]:
arr.sum()

36

In [5]:
arr.mean(axis=1)

array([1., 4., 7.])

In [8]:
arr.sum(0)  # 0 列和

array([ 9, 12, 15])

In [9]:
arr.max()

8

In [10]:
arr.min()

0

In [11]:
arr.argmax()

8

In [12]:
arr.argmax(1)

array([2, 2, 2], dtype=int64)

In [15]:
arr.argmin(1)

array([0, 0, 0], dtype=int64)

In [16]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [19]:
arr.cumsum(1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [18]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [21]:
arr.cumprod(0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

In [26]:
arr = np.random.randn(100)
(arr > 0).sum()

48

In [28]:
bools = np.array([False, False, True, False])
bools.any()

True

In [29]:
bools.all()

False

In [30]:
arr = np.arange(5)
arr.any()

True

In [31]:
arr.all()

False

In [38]:
arr = np.arange(9, 0, -1).reshape(3,3)
arr

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [39]:
arr.sort()
arr

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [40]:
arr.sort(1)
arr

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [41]:
arr.sort(0)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### exercise

In [62]:
import numpy as np
# 13
arr1 = np.random.randn(100).reshape(10,10)
print(arr1.max())
print(arr1.min())

# 14 
arr2 = np.random.randn(30)
print(arr2.mean())

# 40
arr3 = np.random.randn(10)
arr3.sort()
print(arr3)

# 45
arr4 = np.random.randn(10)
arr4[arr4.argmax()] = 0
print(arr4)


1.5677191794014353
-2.7602910595676233
0.24115240216773368
[-1.40680269 -0.76824314 -0.58486054 -0.1197565   0.26705151  0.38687719
  0.8675678   1.36879088  1.45356461  1.88594549]
[-0.00227537  1.30790079  0.07053984 -1.01466417  1.68582493  0.
 -0.75737603 -0.44300086  0.27920333 -0.28376843]


## NumPy - 6 (where / 随机数 / 文件I/O)

### 条件逻辑转为数组运算

In [63]:
grade = np.where(score >= 60, 1, -1).astype(str)
grade = np.where(grade=='1', 'P', 'F')

NameError: name 'score' is not defined

In [64]:
result = []
for i in range(n):
    if condition1[i] and condition2[i]:
        result.append(0)
    elif condition1[i]:
        result.append(1)
    elif condition2[i]:
        result.append(2)
    else:
        result.append(3)
        
np.where(condition1 & condition2, 0, np.where(condition1, 1, np.where(condition2, 2, 3)))

NameError: name 'n' is not defined

### NumPy中的随机数

In [65]:
arr = np.random.randn(3,3)
arr.mean()

0.024564402346904195

In [66]:
arr.std()

0.6125646712155574

In [67]:
arr

array([[ 0.65377881,  0.11524491, -0.46222104],
       [-0.44682853, -0.79397414,  1.21531598],
       [ 0.30391051, -0.54434881,  0.18020193]])

### 用于数组的文件I/O

In [68]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.save('an_array', arr)

In [70]:
np.load('an_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr2 = np.arange(10, 20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [72]:
np.savez('array.npz', a=arr, b=arr2)

In [74]:
content = np.load('array.npz')
content['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
content['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [76]:
content

In [77]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.savetxt('test_file.txt', arr, delimiter=',')

In [79]:
np.loadtxt('test_file.txt', delimiter=',')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## NumPy简单入门-7 T / transpose / 线性代数 / 合并 / 拆分

### T

In [81]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### np.transpose

In [84]:
'transpose是对轴进行变换的操作'

'transpose是对轴进行变换的操作'

In [83]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [88]:
arr.transpose((0,2,1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### 线性代数

In [89]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.dot(arr, arr)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [91]:
arr.dot(arr)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [92]:
arr @ arr

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

### np.concatenate

In [93]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
np.concatenate([arr1,arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [95]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [96]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### np.split

In [97]:
arr = np.random.randn(5,2)
arr

array([[-1.63097483,  0.76073609],
       [ 0.85094799,  1.38860501],
       [-1.35196814,  0.10784952],
       [-0.38118849, -0.2267515 ],
       [-0.19823415, -1.47827719]])

In [98]:
first, second, third = np.split(arr, [1,3])
first

array([[-1.63097483,  0.76073609]])

In [99]:
second

array([[ 0.85094799,  1.38860501],
       [-1.35196814,  0.10784952]])

In [100]:
third

array([[-0.38118849, -0.2267515 ],
       [-0.19823415, -1.47827719]])

In [105]:
np.vsplit(arr, 5)

[array([[-1.63097483,  0.76073609]]),
 array([[0.85094799, 1.38860501]]),
 array([[-1.35196814,  0.10784952]]),
 array([[-0.38118849, -0.2267515 ]]),
 array([[-0.19823415, -1.47827719]])]

In [107]:
np.hsplit(arr,2)

[array([[-1.63097483],
        [ 0.85094799],
        [-1.35196814],
        [-0.38118849],
        [-0.19823415]]),
 array([[ 0.76073609],
        [ 1.38860501],
        [ 0.10784952],
        [-0.2267515 ],
        [-1.47827719]])]

### exercise

In [123]:
import numpy as np
# 18
arr1 = np.diag(1 + np.arange(4), k=-1)
print(arr1)

# 24
arr2 = np.arange(15).reshape(5,3)
arr3 = np.arange(6).reshape(3,2)
arr2.dot(arr3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

## NumPy - 8 (广播 / ufunc补充)